import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:genui_min/genui_min.dart';
import 'package:json_schema_builder/json_schema_builder.dart' as jsb;

// The worked few-shot example from the minimal system prompt — a message any
// conforming model (or constrained decoder) must be able to produce.
const _good = {
  'version': 'v0.9',
  'updateComponents': {
    'surfaceId': 'main',
    'components': [
      {
        'id': 'root',
        'component': 'Column',
        'children': ['info_card', 'cta_button'],
      },
      {'id': 'info_card', 'component': 'Card', 'child': 'card_text'},
      {
        'id': 'card_text',
        'component': 'Text',
        'text': 'Drink water before coffee.',
      },
      {
        'id': 'cta_button',
        'component': 'Button',
        'child': 'cta_label',
        'action': {
          'event': {'name': 'cta_clicked', 'context': {}},
        },
      },
      {'id': 'cta_label', 'component': 'Text', 'text': 'Got it'},
      {
        'id': 'score',
        'component': 'Stat',
        'value': '66',
        'label': 'Glow score',
        'delta': '+4',
        'trend': 'up',
      },
    ],
  },
};

Object _typed(Object v) => jsonDecode(jsonEncode(v));

void main() {
  final catalog = styledMinimalCatalog();
  final schema = updateComponentsOutputSchema(catalog);

  test('schema accepts a known-good updateComponents message', () async {
    final errs = await jsb.Schema.fromMap(schema).validate(_typed(_good));
    expect(errs, isEmpty);
  });

  test('schema rejects an unknown component type', () async {
    final bad = _typed({
      ..._good,
      'updateComponents': {
        'surfaceId': 'main',
        'components': [
          {'id': 'x', 'component': 'Row', 'children': []},
        ],
      },
    });
    final errs = await jsb.Schema.fromMap(schema).validate(bad);
    expect(errs, isNotEmpty);
  });

  test('schema rejects a Button without an action', () async {
    final bad = _typed({
      ..._good,
      'updateComponents': {
        'surfaceId': 'main',
        'components': [
          {'id': 'b', 'component': 'Button', 'child': 'l'},
        ],
      },
    });
    final errs = await jsb.Schema.fromMap(schema).validate(bad);
    expect(errs, isNotEmpty);
  });

  test('every component branch requires a unique-id property, first', () {
    final update = (schema['properties'] as Map)['updateComponents']
        as Map<Object?, Object?>;
    final components =
        (update['properties'] as Map)['components'] as Map<Object?, Object?>;
    final oneOf = (components['items'] as Map)['oneOf'] as List;
    expect(oneOf, hasLength(5));
    for (final alt in oneOf) {
      final props = (alt as Map)['properties'] as Map;
      final required = (alt['required'] as List).cast<String>();
      expect(props.keys.first, 'id');
      expect(props.keys.elementAt(1), 'component');
      expect(required, containsAll(['id', 'component']));
    }
  });

  test(
    'grammar artifacts are current '
    '(regen: GENUI_MIN_REGEN=1 flutter test test/constrained_test.dart)',
    () {
      final schemaJson = updateComponentsOutputSchemaJson(catalog);
      final gbnf = updateComponentsGbnf(catalog);
      final schemaFile = File('grammar/a2ui-min.schema.json');
      final gbnfFile = File('grammar/a2ui-min.gbnf');

      if (Platform.environment['GENUI_MIN_REGEN'] == '1') {
        Directory('grammar').createSync(recursive: true);
        schemaFile.writeAsStringSync(schemaJson);
        gbnfFile.writeAsStringSync(gbnf);
        return;
      }

      expect(
        schemaFile.existsSync() && gbnfFile.existsSync(),
        isTrue,
        reason: 'artifacts missing — regenerate them (see test name)',
      );
      expect(schemaFile.readAsStringSync(), schemaJson);
      expect(gbnfFile.readAsStringSync(), gbnf);
    },
  );

  test('gbnf grammar covers the minimal catalog with well-formed primitives',
      () {
    final g = updateComponentsGbnf(catalog);
    expect(g, startsWith('# Generated by genui_min'));
    expect(g, contains('root ::= '));
    for (final component in ['Text', 'Card', 'Button', 'Column', 'Stat']) {
      expect(g, contains('"$component"'));
    }
    // The canonical string rule, with its properly-closed trailing literal.
    expect(g, contains(r'string ::= "\""'));
    expect(g, contains(r'* "\""' '\n'));
    // Component objects require id before component.
    expect(g, contains(RegExp(r'"id" ws ":" ws r\d+ "," ws "component"')));
  });
}
