// JSON Schema (as a plain map) → GBNF grammar, for llama.cpp-family
// constrained decoding (llama-server grammars, llama.cpp `--grammar`, LM
// Studio, …).
//
// The goal is not full JSON Schema coverage — it's a robust converter for the
// schemas genui emits (objects, enums, arrays, oneOf discriminators), with a
// permissive JSON-value fallback for anything unrecognized so generation never
// dead-ends. Two documented limitations, deliberate to keep grammars small
// and models unstuck:
//
//   * object properties are emitted in schema order (constrained decoding
//     walks one path anyway; fixed order costs little),
//   * when an object has NO required properties, the optional group is
//     all-or-nothing (empty or all, in order).
//
// Pure Dart, no Flutter deps.

import 'dart:convert';

/// Convert [schema] (a JSON Schema object) into a GBNF grammar string whose
/// `root` rule accepts exactly the JSON the schema describes.
String gbnfFromJsonSchema(Map<String, Object?> schema) {
  final gen = _GbnfGenerator();
  final root = gen.ruleFor(schema);
  final buffer = StringBuffer()
    ..writeln('# Generated by genui_min (gbnfFromJsonSchema).')
    ..writeln('# Constrained-decoding grammar: only schema-valid JSON is')
    ..writeln('# producible. Unknown constructs fall back to permissive JSON.')
    ..writeln('root ::= $root ws')
    ..writeln();
  for (final rule in gen.prelude) {
    buffer.writeln(rule);
  }
  for (final rule in gen.rules) {
    buffer.writeln(rule);
  }
  return buffer.toString();
}

final class _GbnfGenerator {
  // JSON primitives, verbatim from llama.cpp's canonical json.gbnf (raw
  // string: every backslash is significant and must survive to the output).
  static const _preludeText = r'''
ws ::= [ \t\n\r]*
string ::= "\"" ( [^"\\\x7F\x00-\x1F] | "\\" (["\\bfnrt] | "u" [0-9a-fA-F]{4}) )* "\""
integer ::= ("0" | [1-9] [0-9]{0,15})
number ::= ("-"? integer) ("." [0-9]{0,16} ([eE] [-+]? [0-9]{1,10})?)?
boolean ::= "true" | "false"
null-literal ::= "null"
any-value ::= any-object | any-array | string | number | boolean | null-literal
any-array ::= "[" ws ( any-value ("," ws any-value)* )? "]"
any-object ::= "{" ws ( string ws ":" ws any-value ("," ws string ws ":" ws any-value)* )? "}"
''';

  final prelude = _preludeText.trim().split('\n');
  final rules = <String>[];
  final _bySchema = <String, String>{}; // canonical subschema → rule name
  var _next = 0;

  String ruleFor(Object? schema) {
    if (schema is! Map) return 'any-value'; // boolean/absent schema: anything
    final key = jsonEncode(schema);
    final existing = _bySchema[key];
    if (existing != null) return existing;
    final name = 'r${_next++}';
    // Reserve the name before recursing so identical children dedup cleanly.
    _bySchema[key] = name;
    rules.add('$name ::= ${_definitionFor(schema)}');
    return name;
  }

  String _definitionFor(Map schema) {
    // oneOf / anyOf → alternatives.
    for (final combinator in ['oneOf', 'anyOf']) {
      final alts = schema[combinator];
      if (alts is List && alts.isNotEmpty) {
        return [for (final a in alts) ruleFor(a)].join(' | ');
      }
    }

    final type = schema['type'];
    if (schema.containsKey('enum')) return _enum(schema['enum'] as List);
    if (schema.containsKey('const')) return _literal(schema['const']);
    if (type == 'string') return 'string';
    if (type == 'integer') return 'integer';
    if (type == 'number') return 'number';
    if (type == 'boolean') return 'boolean';
    if (type == 'null') return 'null-literal';
    if (type == 'array') return _array(schema);
    if (type == 'object') return _object(schema);

    // No/unknown type: permissive.
    return 'any-value';
  }

  String _array(Map schema) {
    final itemRule = ruleFor(schema['items']);
    return '"[" ws ( $itemRule ("," ws $itemRule)* )? "]"';
  }

  String _object(Map schema) {
    final props = schema['properties'];
    final required =
        (schema['required'] as List?)?.toSet() ?? const <String?>{};
    final isPermissive = schema['additionalProperties'] == true;
    if (isPermissive || props is! Map || props.isEmpty) return 'any-object';

    final members = <String>[]; // required, in schema order
    final optional = <String>[]; // optional, in schema order
    for (final e in props.entries) {
      final member = '${_literal(e.key)} ws ":" ws ${ruleFor(e.value)}';
      if (required.contains(e.key)) {
        members.add(member);
      } else {
        optional.add(member);
      }
    }

    var body = members.join(' "," ws ');
    if (members.isEmpty && optional.isNotEmpty) {
      // Optional-only object: whole group all-or-nothing (see header note).
      body = '(${optional.join(' "," ws ')})?';
    } else {
      for (final m in optional) {
        body = '$body ("," ws $m)?';
      }
    }
    if (body.isEmpty) return '"{" ws "}"';
    return '"{" ws $body "}"';
  }

  String _enum(List values) => values.map(_literal).join(' | ');

  /// A GBNF string literal for [value] (keys, enums, consts).
  String _literal(Object? value) {
    final s = value.toString();
    final escaped = s
        .replaceAll(r'\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n')
        .replaceAll('\t', r'\t')
        .replaceAll('\r', r'\r');
    return '"$escaped"';
  }
}
